[build]
  command = "curl -sL https://github.com/gohugoio/hugo/releases/download/v0.40.1/hugo_0.40.1_Linux-64bit.tar.gz | tar xz && ./hugo --gc"
  publish = "public"

[build.environment]
  HUGO_ENABLEGITINFO = "true"
